#Sample _config.yml

title: Zen-Doshay
author:
 name: Warren G. Martin
 email: 
   personal: example@personal
   school: example@school
 github_username: zendosha
header_pages:
 - index.md
 - blog.md
 - about.md
 - cv.md
message: Comparison is the theif of joy.
style: dark
google_analytics: G-NNNNNNNNNN


remote_theme: zendosha/zendosha.github.io

