#Sample _config.yml

title: Zen-Dosha
author:
 name: Warren G. Martin
 email: 
   personal: example@personal
   school: example@school
 github_username: zendosha
header_pages:
 - Home.md
 - another_page.md
message: Write some cool footer message here
style: dark
google_analytics: G-NNNNNNNNNN


remote_theme: zendosha/zendosha.github.io
